spring:
 datasource:
  #url:  jdbc:mysql://10.10.10.254/test?useUnicode=true&characterEncoding=UTF-8
  url:  jdbc:mysql://localhost:3306/mytest?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
  username: root
  password: root123

server:
 port: 8088

mybatis-plus:
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
